# Generated by Django 5.0.6 on 2024-05-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("adresse", models.TextField()),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("date_naissance", models.DateField()),
                ("numero_contrat", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
