# Generated by Django 5.0.6 on 2024-05-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="numero_contrat",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
